INSERT INTO roles (name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN'
);

INSERT INTO roles (name)
SELECT 'ROLE_EMPLOYEE'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_EMPLOYEE'
);

INSERT INTO roles (name)
SELECT 'ROLE_SERVICE_PERSONNEL'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_SERVICE_PERSONNEL'
);