import { alpha, createTheme } from '@mui/material/styles';

const rawColors = {
  base: {
    light: '#ffffff',
    dark: '#000000',
  },
  brand: {
    primary: '#0082c4',
    primaryHover: '#006fa7',
    primaryHoverAlt: '#00689d',
    primaryPressed: '#00567f',
    primaryCardHover: '#0077b4',
    gradientMid: '#4da8d6',
    gradientGold: '#4da8d6',
    accent: '#4da8d6',
    sidebarActive: '#00689d',
    sidebarActiveText: '#ffffff',
    react: '#61dafb',
  },
  surface: {
    page: '#ffffff',
    paper: '#ffffff',
    subtle: '#f3f3f3',
    tooltip: '#f5f5f9',
    calendarControl: '#dff2fb',
    calendarControlHover: '#cfeaf7',
    iconHover: '#f1f1f1',
    panel: '#f9f9f9',
    input: '#eef4ff',
    info: '#eaf2fb',
    success: '#e4f3ea',
    successHover: '#d7ecdf',
    warning: '#fff4e5',
    mutedOverlay: '#aba8a8',
  },
  text: {
    primary: '#000000',
    body: '#333333',
    inverse: '#ffffff',
    muted: '#1f1f1f',
    accent: '#0082c4',
    warning: '#8a3b00',
    error: '#d32f2f',
    errorDark: '#b71c1c',
    disabled: '#888888',
    eventDefault: '#505050',
    appHeader: '#282c34',
  },
  border: {
    default: '#dadde9',
    muted: '#cccccc',
    faint: '#dddddd',
    calendarControl: '#b7dbea',
    success: '#b7e0c8',
    warning: '#f0b36a',
  },
  state: {
    favouriteActive: '#ffb300',
    tableHeader: '#0082c4',
    actionPositive: '#69be28',
    neutralGrey: '#808080',
    neutral: '#9e9e9e',
    neutralMid: '#7a7a7a',
    neutralDark: '#757575',
    deskBlocked: '#bdbdbd',
    deskAvailable: '#69be28',
    carparkHover: '#90caf9',
    carparkSelected: '#1976d2',
    carparkAvailable: '#2e7d32',
    carparkPending: '#f9a825',
    carparkOccupied: '#c62828',
    carparkBlocked: '#9e9e9e',
    carparkInactive: '#ffffff',
    calendarMine: '#0082c4',
    calendarMinePending: '#f9a825',
    calendarPendingOther: '#c9c9c9',
    defectLow: '#4caf50',
    defectMedium: '#ff9800',
    defectHigh: '#f44336',
    defectCritical: '#b71c1c',
    defectNew: '#1976d2',
    defectInProgress: '#ed6c02',
    defectResolved: '#2e7d32',
    mapDefault: '#0000ff',
    mapSelected: '#008000',
    mapDelete: '#ff0000',
  },
};

const computedValues = {
  overlayScrim: alpha(rawColors.base.dark, 0.5),
  overlayPanel: alpha(rawColors.surface.mutedOverlay, 0.5),
  textStrong: alpha(rawColors.base.dark, 0.87),
  borderStrong: alpha(rawColors.base.dark, 0.23),
  borderLight: alpha(rawColors.base.light, 0.6),
  borderLightStrong: alpha(rawColors.base.light, 0.9),
  surfaceTranslucent: alpha(rawColors.base.light, 0.08),
  shadowSoft: `0 2px 4px ${alpha(rawColors.base.dark, 0.1)}`,
  shadowSoftStrong: `0 2px 4px ${alpha(rawColors.base.dark, 0.12)}`,
  shadowCard: `0 2px 6px ${alpha(rawColors.base.dark, 0.08)}`,
  shadowGlowSoft: `0 0 10px ${alpha(rawColors.base.dark, 0.1)}`,
  shadowGlow: `0 0 10px ${alpha(rawColors.base.dark, 0.2)}`,
  shadowDesk: `0 0 5px ${alpha(rawColors.base.dark, 0.2)}`,
  shadowDeskHover: `0 0 10px ${alpha(rawColors.base.dark, 0.4)}`,
  gradientBrand: `linear-gradient(90deg, ${rawColors.brand.primary} 0%, ${rawColors.brand.gradientMid} 21%, ${rawColors.brand.gradientGold} 81%, ${rawColors.brand.accent} 100%)`,
};

const cssVariables = {
  '--color-base-light': rawColors.base.light,
  '--color-base-dark': rawColors.base.dark,
  '--color-brand-primary': rawColors.brand.primary,
  '--color-brand-primary-hover': rawColors.brand.primaryHover,
  '--color-brand-primary-hover-alt': rawColors.brand.primaryHoverAlt,
  '--color-brand-primary-pressed': rawColors.brand.primaryPressed,
  '--color-brand-primary-card-hover': rawColors.brand.primaryCardHover,
  '--color-brand-gradient-mid': rawColors.brand.gradientMid,
  '--color-brand-gradient-gold': rawColors.brand.gradientGold,
  '--color-brand-accent': rawColors.brand.accent,
  '--color-brand-sidebar-active': rawColors.brand.sidebarActive,
  '--color-brand-sidebar-active-text': rawColors.brand.sidebarActiveText,
  '--color-brand-react': rawColors.brand.react,
  '--color-surface-page': rawColors.surface.page,
  '--color-surface-paper': rawColors.surface.paper,
  '--color-surface-subtle': rawColors.surface.subtle,
  '--color-surface-tooltip': rawColors.surface.tooltip,
  '--color-surface-calendar-control': rawColors.surface.calendarControl,
  '--color-surface-calendar-control-hover': rawColors.surface.calendarControlHover,
  '--color-surface-icon-hover': rawColors.surface.iconHover,
  '--color-surface-panel': rawColors.surface.panel,
  '--color-surface-input': rawColors.surface.input,
  '--color-surface-info': rawColors.surface.info,
  '--color-surface-success': rawColors.surface.success,
  '--color-surface-success-hover': rawColors.surface.successHover,
  '--color-surface-warning': rawColors.surface.warning,
  '--color-text-primary': rawColors.text.primary,
  '--color-text-body': rawColors.text.body,
  '--color-text-inverse': rawColors.text.inverse,
  '--color-text-muted': rawColors.text.muted,
  '--color-text-accent': rawColors.text.accent,
  '--color-text-warning': rawColors.text.warning,
  '--color-text-error': rawColors.text.error,
  '--color-text-error-dark': rawColors.text.errorDark,
  '--color-text-disabled': rawColors.text.disabled,
  '--color-text-event-default': rawColors.text.eventDefault,
  '--color-text-app-header': rawColors.text.appHeader,
  '--color-border-default': rawColors.border.default,
  '--color-border-muted': rawColors.border.muted,
  '--color-border-faint': rawColors.border.faint,
  '--color-border-calendar-control': rawColors.border.calendarControl,
  '--color-border-success': rawColors.border.success,
  '--color-border-warning': rawColors.border.warning,
  '--color-state-favourite-active': rawColors.state.favouriteActive,
  '--color-state-table-header': rawColors.state.tableHeader,
  '--color-state-action-positive': rawColors.state.actionPositive,
  '--color-state-neutral-grey': rawColors.state.neutralGrey,
  '--color-state-neutral': rawColors.state.neutral,
  '--color-state-neutral-mid': rawColors.state.neutralMid,
  '--color-state-neutral-dark': rawColors.state.neutralDark,
  '--color-state-desk-blocked': rawColors.state.deskBlocked,
  '--color-state-desk-available': rawColors.state.deskAvailable,
  '--color-state-carpark-hover': rawColors.state.carparkHover,
  '--color-state-carpark-selected': rawColors.state.carparkSelected,
  '--color-state-carpark-available': rawColors.state.carparkAvailable,
  '--color-state-carpark-pending': rawColors.state.carparkPending,
  '--color-state-carpark-occupied': rawColors.state.carparkOccupied,
  '--color-state-carpark-blocked': rawColors.state.carparkBlocked,
  '--color-state-carpark-inactive': rawColors.state.carparkInactive,
  '--color-state-calendar-mine': rawColors.state.calendarMine,
  '--color-state-calendar-mine-pending': rawColors.state.calendarMinePending,
  '--color-state-calendar-pending-other': rawColors.state.calendarPendingOther,
  '--color-state-defect-low': rawColors.state.defectLow,
  '--color-state-defect-medium': rawColors.state.defectMedium,
  '--color-state-defect-high': rawColors.state.defectHigh,
  '--color-state-defect-critical': rawColors.state.defectCritical,
  '--color-state-defect-new': rawColors.state.defectNew,
  '--color-state-defect-in-progress': rawColors.state.defectInProgress,
  '--color-state-defect-resolved': rawColors.state.defectResolved,
  '--color-state-map-default': rawColors.state.mapDefault,
  '--color-state-map-selected': rawColors.state.mapSelected,
  '--color-state-map-delete': rawColors.state.mapDelete,
  '--color-overlay-scrim': computedValues.overlayScrim,
  '--color-overlay-panel': computedValues.overlayPanel,
  '--color-text-strong': computedValues.textStrong,
  '--color-border-strong': computedValues.borderStrong,
  '--color-border-light': computedValues.borderLight,
  '--color-border-light-strong': computedValues.borderLightStrong,
  '--color-surface-translucent': computedValues.surfaceTranslucent,
  '--shadow-soft': computedValues.shadowSoft,
  '--shadow-soft-strong': computedValues.shadowSoftStrong,
  '--shadow-card': computedValues.shadowCard,
  '--shadow-glow-soft': computedValues.shadowGlowSoft,
  '--shadow-glow': computedValues.shadowGlow,
  '--shadow-desk': computedValues.shadowDesk,
  '--shadow-desk-hover': computedValues.shadowDeskHover,
  '--gradient-brand': computedValues.gradientBrand,
};

const varRef = (name) => `var(${name})`;

export const colorVars = {
  base: {
    light: varRef('--color-base-light'),
    dark: varRef('--color-base-dark'),
  },
  brand: {
    primary: varRef('--color-brand-primary'),
    primaryHover: varRef('--color-brand-primary-hover'),
    primaryHoverAlt: varRef('--color-brand-primary-hover-alt'),
    primaryPressed: varRef('--color-brand-primary-pressed'),
    primaryCardHover: varRef('--color-brand-primary-card-hover'),
    accent: varRef('--color-brand-accent'),
    sidebarActive: varRef('--color-brand-sidebar-active'),
    sidebarActiveText: varRef('--color-brand-sidebar-active-text'),
    react: varRef('--color-brand-react'),
  },
  surface: {
    page: varRef('--color-surface-page'),
    paper: varRef('--color-surface-paper'),
    subtle: varRef('--color-surface-subtle'),
    tooltip: varRef('--color-surface-tooltip'),
    calendarControl: varRef('--color-surface-calendar-control'),
    calendarControlHover: varRef('--color-surface-calendar-control-hover'),
    iconHover: varRef('--color-surface-icon-hover'),
    panel: varRef('--color-surface-panel'),
    input: varRef('--color-surface-input'),
    info: varRef('--color-surface-info'),
    success: varRef('--color-surface-success'),
    successHover: varRef('--color-surface-success-hover'),
    warning: varRef('--color-surface-warning'),
    translucent: varRef('--color-surface-translucent'),
  },
  text: {
    primary: varRef('--color-text-primary'),
    body: varRef('--color-text-body'),
    inverse: varRef('--color-text-inverse'),
    muted: varRef('--color-text-muted'),
    accent: varRef('--color-text-accent'),
    warning: varRef('--color-text-warning'),
    error: varRef('--color-text-error'),
    errorDark: varRef('--color-text-error-dark'),
    disabled: varRef('--color-text-disabled'),
    eventDefault: varRef('--color-text-event-default'),
    appHeader: varRef('--color-text-app-header'),
    strong: varRef('--color-text-strong'),
  },
  border: {
    default: varRef('--color-border-default'),
    muted: varRef('--color-border-muted'),
    faint: varRef('--color-border-faint'),
    calendarControl: varRef('--color-border-calendar-control'),
    success: varRef('--color-border-success'),
    warning: varRef('--color-border-warning'),
    strong: varRef('--color-border-strong'),
    light: varRef('--color-border-light'),
    lightStrong: varRef('--color-border-light-strong'),
  },
  state: {
    favouriteActive: varRef('--color-state-favourite-active'),
    tableHeader: varRef('--color-state-table-header'),
    actionPositive: varRef('--color-state-action-positive'),
    neutralGrey: varRef('--color-state-neutral-grey'),
    neutral: varRef('--color-state-neutral'),
    neutralMid: varRef('--color-state-neutral-mid'),
    neutralDark: varRef('--color-state-neutral-dark'),
    deskBlocked: varRef('--color-state-desk-blocked'),
    deskAvailable: varRef('--color-state-desk-available'),
    carparkHover: varRef('--color-state-carpark-hover'),
    carparkSelected: varRef('--color-state-carpark-selected'),
    carparkAvailable: varRef('--color-state-carpark-available'),
    carparkPending: varRef('--color-state-carpark-pending'),
    carparkOccupied: varRef('--color-state-carpark-occupied'),
    carparkBlocked: varRef('--color-state-carpark-blocked'),
    carparkInactive: varRef('--color-state-carpark-inactive'),
    calendarMine: varRef('--color-state-calendar-mine'),
    calendarMinePending: varRef('--color-state-calendar-mine-pending'),
    calendarPendingOther: varRef('--color-state-calendar-pending-other'),
    defectLow: varRef('--color-state-defect-low'),
    defectMedium: varRef('--color-state-defect-medium'),
    defectHigh: varRef('--color-state-defect-high'),
    defectCritical: varRef('--color-state-defect-critical'),
    defectNew: varRef('--color-state-defect-new'),
    defectInProgress: varRef('--color-state-defect-in-progress'),
    defectResolved: varRef('--color-state-defect-resolved'),
    mapDefault: varRef('--color-state-map-default'),
    mapSelected: varRef('--color-state-map-selected'),
    mapDelete: varRef('--color-state-map-delete'),
  },
  overlay: {
    scrim: varRef('--color-overlay-scrim'),
    panel: varRef('--color-overlay-panel'),
  },
  shadow: {
    soft: varRef('--shadow-soft'),
    softStrong: varRef('--shadow-soft-strong'),
    card: varRef('--shadow-card'),
    glowSoft: varRef('--shadow-glow-soft'),
    glow: varRef('--shadow-glow'),
    desk: varRef('--shadow-desk'),
    deskHover: varRef('--shadow-desk-hover'),
  },
  gradient: {
    brand: varRef('--gradient-brand'),
  },
};

export const semanticColors = {
  booking: {
    desk: {
      blocked: varRef('--color-state-desk-blocked'),
      available: varRef('--color-state-desk-available'),
      selected: varRef('--color-brand-accent'),
    },
    event: {
      mine: varRef('--color-state-calendar-mine'),
      minePending: varRef('--color-state-calendar-mine-pending'),
      pendingOther: varRef('--color-state-calendar-pending-other'),
      default: varRef('--color-text-event-default'),
    },
    favourite: {
      active: varRef('--color-state-favourite-active'),
      inactive: varRef('--color-state-neutral'),
    },
  },
  carpark: {
    hover: varRef('--color-state-carpark-hover'),
    selected: varRef('--color-state-carpark-selected'),
    status: {
      AVAILABLE: varRef('--color-state-carpark-available'),
      PENDING: varRef('--color-state-carpark-pending'),
      OCCUPIED: varRef('--color-state-carpark-occupied'),
      BLOCKED: varRef('--color-state-carpark-blocked'),
      INACTIVE: varRef('--color-state-carpark-inactive'),
    },
  },
  defects: {
    urgency: {
      LOW: varRef('--color-state-defect-low'),
      MEDIUM: varRef('--color-state-defect-medium'),
      HIGH: varRef('--color-state-defect-high'),
      CRITICAL: varRef('--color-state-defect-critical'),
    },
    status: {
      NEW: varRef('--color-state-defect-new'),
      IN_PROGRESS: varRef('--color-state-defect-in-progress'),
      RESOLVED: varRef('--color-state-defect-resolved'),
    },
    fallback: varRef('--color-state-neutral'),
  },
  map: {
    existing: varRef('--color-state-map-default'),
    pending: varRef('--color-state-map-selected'),
    destructive: varRef('--color-state-map-delete'),
  },
  destructive: {
    main: varRef('--color-text-error'),
    dark: varRef('--color-text-error-dark'),
  },
  tables: {
    header: varRef('--color-state-table-header'),
  },
};

export const appColorTokens = {
  raw: rawColors,
  vars: colorVars,
  semantic: semanticColors,
};

export const appTheme = createTheme({
  palette: {
    primary: {
      main: rawColors.brand.primary,
    },
    secondary: {
      main: rawColors.brand.accent,
    },
    success: {
      main: rawColors.state.actionPositive,
    },
    warning: {
      main: rawColors.state.defectMedium,
    },
    error: {
      main: rawColors.text.error,
    },
    background: {
      default: rawColors.surface.page,
      paper: rawColors.surface.paper,
    },
    text: {
      primary: rawColors.text.primary,
      secondary: alpha(rawColors.base.dark, 0.6),
    },
  },
  typography: {
    fontFamily: "'Source Sans Pro', sans-serif",
  },
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        ':root': cssVariables,
      },
    },
  },
});

appTheme.appColors = appColorTokens;
